### PR TITLE
Ansible 2.1.1: 1 Warning, 1 Deprecation

### PR DESCRIPTION
**Pull request by jonaseberle**

### CODE REVIEW

**Comment by tersmitten** [comment]
Thanks for your contribution! 

I rather not drop support for Ansible < 1.9 (yet). Can you you split the pull request so I can merge part of it now and the rest later (soon).

**Comment by jonaseberle** [comment]
I'll do.

**Comment by tersmitten** [comment]
Thanks

**Comment by tersmitten** [comment]
See #13 and #14

**Pull request closed without merging**
